### ISSUE TITLE
 Class 'DBus' not found in dbus.inc.php:3

### ISSUE THREAD

**Issue by s-s-s** [BrandMeister/bm-rpt2aprs#15]
`connecting to aprs...
PHP Fatal error:  Uncaught Error: Class 'DBus' not found in /home/pi/mmdvm/bm2aprs/dbus.inc.php:3
Stack trace:
#0 /home/pi/mmdvm/bm2aprs/bm-rpt2aprs.php(18): dbus_get_repeater_ids_for_network()
#1 {main}
  thrown in /home/pi/mmdvm/bm2aprs/dbus.inc.php on line 3

Fatal error: Uncaught Error: Class 'DBus' not found in /home/pi/mmdvm/bm2aprs/dbus.inc.php:3
Stack trace:
#0 /home/pi/mmdvm/bm2aprs/bm-rpt2aprs.php(18): dbus_get_repeater_ids_for_network()
#1 {main}
  thrown in /home/pi/mmdvm/bm2aprs/dbus.inc.php on line 3`

**Comment by nonoo** [comment]
First query if the dbus module is loaded in PHP with `php -m | grep dbus`
It should output the string "dbus". If you don't see it, make sure it is loaded by PHP.
